title: "Aprendiendo Java"
default_lang: es

permalink: ":categories/:title"

disqus_shortname: #disabled if left blank

highlighter: pygments
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

